CREATE TABLE `comissoes` (
	`id` varchar(64) NOT NULL,
	`dentistaId` varchar(64) NOT NULL,
	`faturaId` varchar(64),
	`utenteId` varchar(64),
	`dataReferencia` varchar(10) NOT NULL,
	`dataPagamento` varchar(10),
	`valorBase` decimal(10,2) NOT NULL,
	`valorComissao` decimal(10,2) NOT NULL,
	`bonificacao` decimal(10,2) DEFAULT '0',
	`valorTotal` decimal(10,2) NOT NULL,
	`status` enum('a_pagar','pago','cancelado') NOT NULL DEFAULT 'a_pagar',
	`tipoComissao` enum('percentagem','fixo','misto') NOT NULL,
	`percentagemAplicada` decimal(5,2),
	`observacoes` text,
	`formaPagamento` varchar(50),
	`referenciaPagamento` varchar(100),
	`criadoEm` timestamp DEFAULT (now()),
	`criadoPor` varchar(64),
	`atualizadoEm` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `comissoes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `config_clinica` (
	`id` varchar(64) NOT NULL,
	`nomeClinica` varchar(200) NOT NULL,
	`nomeFantasia` varchar(200),
	`razaoSocial` varchar(200) NOT NULL,
	`nif` varchar(9) NOT NULL,
	`numeroRegistro` varchar(50),
	`telefone` varchar(20) NOT NULL,
	`telemovel` varchar(20),
	`email` varchar(320) NOT NULL,
	`website` varchar(200),
	`redesSociais` text,
	`morada` text NOT NULL,
	`anoFundacao` int,
	`numeroFuncionarios` int,
	`especialidades` text,
	`horarioFuncionamento` text,
	`logoPrincipal` text,
	`logoSecundario` text,
	`favicon` text,
	`paletaCores` text,
	`papelTimbrado` text,
	`nomeSistema` varchar(100),
	`slogan` varchar(200),
	`criadoEm` timestamp DEFAULT (now()),
	`atualizadoEm` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `config_clinica_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `config_comissoes` (
	`id` varchar(64) NOT NULL,
	`dentistaId` varchar(64) NOT NULL,
	`tipo` enum('percentagem','fixo','misto','nenhum') NOT NULL DEFAULT 'percentagem',
	`configuracao` text NOT NULL,
	`pagarEm` enum('semanal','quinzenal','mensal') DEFAULT 'mensal',
	`diasPagamento` text,
	`criadoEm` timestamp DEFAULT (now()),
	`atualizadoEm` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `config_comissoes_id` PRIMARY KEY(`id`),
	CONSTRAINT `config_comissoes_dentistaId_unique` UNIQUE(`dentistaId`)
);
--> statement-breakpoint
CREATE TABLE `dentistas` (
	`id` varchar(64) NOT NULL,
	`nome` varchar(200) NOT NULL,
	`nomeCompleto` varchar(200) NOT NULL,
	`foto` text,
	`nif` varchar(9) NOT NULL,
	`numeroOrdem` varchar(20) NOT NULL,
	`especialidades` text NOT NULL,
	`email` varchar(320) NOT NULL,
	`telefone` varchar(20) NOT NULL,
	`telemovel` varchar(20),
	`dataAdmissao` varchar(10) NOT NULL,
	`status` enum('ativo','inativo','ferias','licenca') NOT NULL DEFAULT 'ativo',
	`cargo` varchar(100),
	`horarioTrabalho` text,
	`corAgenda` varchar(7) DEFAULT '#3b82f6',
	`permiteAgendamentoOnline` boolean DEFAULT true,
	`tempoConsultaPadrao` int DEFAULT 30,
	`observacoes` text,
	`competencias` text,
	`idiomas` text,
	`criadoEm` timestamp DEFAULT (now()),
	`atualizadoEm` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `dentistas_id` PRIMARY KEY(`id`),
	CONSTRAINT `dentistas_numeroOrdem_unique` UNIQUE(`numeroOrdem`)
);
--> statement-breakpoint
CREATE TABLE `formas_pagamento` (
	`id` varchar(64) NOT NULL,
	`nome` varchar(100) NOT NULL,
	`tipo` varchar(50) NOT NULL,
	`ativo` boolean DEFAULT true,
	`icone` varchar(50),
	`cor` varchar(7),
	`ordem` int DEFAULT 0,
	`taxa` text,
	`valorMinimo` decimal(10,2),
	`valorMaximo` decimal(10,2),
	`integracao` text,
	`observacoes` text,
	`requerReferencia` boolean DEFAULT false,
	`criadoEm` timestamp DEFAULT (now()),
	`atualizadoEm` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `formas_pagamento_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `funcionarios` (
	`id` varchar(64) NOT NULL,
	`nome` varchar(200) NOT NULL,
	`foto` text,
	`nif` varchar(9) NOT NULL,
	`numeroSegSocial` varchar(20),
	`email` varchar(320) NOT NULL,
	`telefone` varchar(20) NOT NULL,
	`cargo` varchar(100) NOT NULL,
	`dataAdmissao` varchar(10) NOT NULL,
	`status` enum('ativo','inativo','ferias','licenca') NOT NULL DEFAULT 'ativo',
	`horarioTrabalho` text,
	`salario` text,
	`usuario` text,
	`criadoEm` timestamp DEFAULT (now()),
	`atualizadoEm` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `funcionarios_id` PRIMARY KEY(`id`)
);
