CREATE TABLE `cadastro_laboratorios` (
	`id` varchar(64) NOT NULL,
	`nome` varchar(200) NOT NULL,
	`razaoSocial` varchar(200),
	`nif` varchar(9),
	`telefone` varchar(20) NOT NULL,
	`telemovel` varchar(20),
	`email` varchar(320),
	`whatsapp` varchar(20),
	`website` varchar(200),
	`morada` text,
	`cidade` varchar(100),
	`codigoPostal` varchar(10),
	`pais` varchar(50) DEFAULT 'Portugal',
	`responsavelTecnico` varchar(200),
	`especialidades` text,
	`prazoMedioEntrega` int DEFAULT 7,
	`formasPagamentoAceitas` text,
	`condicoesPagamento` varchar(200),
	`status` enum('ativo','inativo') NOT NULL DEFAULT 'ativo',
	`avaliacaoQualidade` int DEFAULT 5,
	`observacoes` text,
	`criadoEm` timestamp DEFAULT (now()),
	`criadoPor` varchar(64),
	`atualizadoEm` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cadastro_laboratorios_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `categorias_despesa` (
	`id` varchar(64) NOT NULL,
	`nome` varchar(100) NOT NULL,
	`descricao` text,
	`tipo` enum('fixa','variavel') NOT NULL,
	`icone` varchar(50),
	`cor` varchar(7),
	`categoriaPai` varchar(64),
	`ordem` int DEFAULT 0,
	`ativo` boolean DEFAULT true,
	`criadoEm` timestamp DEFAULT (now()),
	`atualizadoEm` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `categorias_despesa_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `contas_pagar` (
	`id` varchar(64) NOT NULL,
	`fornecedorId` varchar(64),
	`categoriaId` varchar(64) NOT NULL,
	`trabalhoLaboratorioId` varchar(64),
	`descricao` varchar(255) NOT NULL,
	`numeroDocumento` varchar(50),
	`valor` decimal(10,2) NOT NULL,
	`valorPago` decimal(10,2) DEFAULT '0',
	`valorRestante` decimal(10,2) NOT NULL,
	`dataEmissao` varchar(10) NOT NULL,
	`dataVencimento` varchar(10) NOT NULL,
	`dataPagamento` varchar(10),
	`status` enum('pendente','paga','parcial','vencida','cancelada') NOT NULL DEFAULT 'pendente',
	`recorrente` boolean DEFAULT false,
	`frequenciaRecorrencia` enum('mensal','trimestral','semestral','anual'),
	`anexos` text,
	`observacoes` text,
	`criadoEm` timestamp DEFAULT (now()),
	`criadoPor` varchar(64),
	`atualizadoEm` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `contas_pagar_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `contas_receber` (
	`id` varchar(64) NOT NULL,
	`utenteId` varchar(64) NOT NULL,
	`dentistaId` varchar(64),
	`consultaId` varchar(64),
	`numeroFatura` varchar(50) NOT NULL,
	`serie` varchar(10) DEFAULT 'FT',
	`tipo` enum('fatura','recibo','fatura_recibo','nota_credito') NOT NULL DEFAULT 'fatura',
	`subtotal` decimal(10,2) NOT NULL,
	`descontoTotal` decimal(10,2) DEFAULT '0',
	`ivaTotal` decimal(10,2) DEFAULT '0',
	`total` decimal(10,2) NOT NULL,
	`valorPago` decimal(10,2) DEFAULT '0',
	`valorRestante` decimal(10,2) NOT NULL,
	`dentistaPercentagem` decimal(5,2) DEFAULT '0',
	`dentistaComissao` decimal(10,2) DEFAULT '0',
	`valorClinica` decimal(10,2) DEFAULT '0',
	`dataEmissao` varchar(10) NOT NULL,
	`dataVencimento` varchar(10) NOT NULL,
	`status` enum('pendente','paga','parcial','vencida','cancelada') NOT NULL DEFAULT 'pendente',
	`itens` text NOT NULL,
	`observacoes` text,
	`criadoEm` timestamp DEFAULT (now()),
	`criadoPor` varchar(64),
	`atualizadoEm` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `contas_receber_id` PRIMARY KEY(`id`),
	CONSTRAINT `contas_receber_numeroFatura_unique` UNIQUE(`numeroFatura`)
);
--> statement-breakpoint
CREATE TABLE `fornecedores` (
	`id` varchar(64) NOT NULL,
	`nome` varchar(200) NOT NULL,
	`razaoSocial` varchar(200),
	`nif` varchar(9),
	`tipo` enum('materiais','equipamentos','servicos','laboratorio','outros') NOT NULL,
	`telefone` varchar(20),
	`email` varchar(320),
	`website` varchar(200),
	`morada` text,
	`nomeContato` varchar(200),
	`telefoneContato` varchar(20),
	`emailContato` varchar(320),
	`condicoesPagamento` varchar(200),
	`status` enum('ativo','inativo') NOT NULL DEFAULT 'ativo',
	`observacoes` text,
	`criadoEm` timestamp DEFAULT (now()),
	`atualizadoEm` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `fornecedores_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `movimentos_caixa` (
	`id` varchar(64) NOT NULL,
	`tipo` enum('entrada','saida','abertura','fechamento','sangria','reforco') NOT NULL,
	`contaReceberId` varchar(64),
	`contaPagarId` varchar(64),
	`descricao` varchar(255) NOT NULL,
	`valor` decimal(10,2) NOT NULL,
	`formaPagamento` varchar(50) NOT NULL,
	`dataHora` datetime NOT NULL,
	`saldoAnterior` decimal(10,2),
	`saldoAtual` decimal(10,2),
	`observacoes` text,
	`criadoEm` timestamp DEFAULT (now()),
	`criadoPor` varchar(64),
	CONSTRAINT `movimentos_caixa_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `pagamentos_contas_pagar` (
	`id` varchar(64) NOT NULL,
	`contaPagarId` varchar(64) NOT NULL,
	`valor` decimal(10,2) NOT NULL,
	`dataPagamento` varchar(10) NOT NULL,
	`formaPagamento` varchar(50) NOT NULL,
	`referencia` varchar(100),
	`comprovante` text,
	`observacoes` text,
	`criadoEm` timestamp DEFAULT (now()),
	`criadoPor` varchar(64),
	CONSTRAINT `pagamentos_contas_pagar_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `pagamentos_contas_receber` (
	`id` varchar(64) NOT NULL,
	`contaReceberId` varchar(64) NOT NULL,
	`valor` decimal(10,2) NOT NULL,
	`dataPagamento` varchar(10) NOT NULL,
	`formaPagamentoId` varchar(64) NOT NULL,
	`referencia` varchar(100),
	`comprovante` text,
	`taxaOperacao` decimal(10,2) DEFAULT '0',
	`valorLiquido` decimal(10,2) NOT NULL,
	`observacoes` text,
	`criadoEm` timestamp DEFAULT (now()),
	`criadoPor` varchar(64),
	CONSTRAINT `pagamentos_contas_receber_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `trabalhos_laboratorio` (
	`id` varchar(64) NOT NULL,
	`laboratorioId` varchar(64) NOT NULL,
	`utenteId` varchar(64) NOT NULL,
	`dentistaId` varchar(64) NOT NULL,
	`consultaId` varchar(64),
	`tipoTrabalho` varchar(100) NOT NULL,
	`descricao` text NOT NULL,
	`dentes` varchar(255),
	`cor` varchar(50),
	`material` varchar(100),
	`dataEnvio` varchar(10),
	`dataPrevisaoEntrega` varchar(10),
	`dataEntregaReal` varchar(10),
	`dataInstalacao` varchar(10),
	`custoLaboratorio` decimal(10,2) NOT NULL,
	`valorCobradoUtente` decimal(10,2),
	`margemLucro` decimal(10,2),
	`status` enum('orcamento','enviado','em_producao','recebido','instalado','ajuste_necessario','cancelado') DEFAULT 'orcamento',
	`avaliacaoQualidade` int,
	`necessitouAjuste` boolean DEFAULT false,
	`observacoes` text,
	`observacoesInternas` text,
	`criadoEm` timestamp DEFAULT (now()),
	`criadoPor` varchar(64),
	`atualizadoEm` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `trabalhos_laboratorio_id` PRIMARY KEY(`id`)
);
